variant = "loose"

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "class-must-be-final"
message = 'Class `Webware\UserManager\Command\CreateUserCommand` should be declared `final`.'
count = 1

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 1

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "redundant-comparison"
message = "Redundant `===` comparison: left-hand side is never identical to right-hand side."
count = 1

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "redundant-condition"
message = "This condition (type `true`) will always evaluate to true."
count = 2

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "redundant-logical-operation"
message = "Redundant `&&` operation: left operand is always truthy and right operand is evaluated."
count = 1

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "redundant-type-comparison"
message = "Redundant type assertion: `$value` is already `string`."
count = 3

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "unreachable-else-clause"
message = "Unreachable else clause"
count = 2

[[issues]]
file = "src/Command/UpdateUserCommand.php"
code = "class-must-be-final"
message = 'Class `Webware\UserManager\Command\UpdateUserCommand` should be declared `final`.'
count = 1

[[issues]]
file = "src/CommandHandler/ToggleUserActiveHandler.php"
code = "non-existent-property"
message = 'Property `$active` does not exist on interface `Webware\Core\UserInterface`.'
count = 1

[[issues]]
file = "src/CommandHandler/UpdateUserHandler.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #1 of `Webware\UserManager\Repository\UserRepositoryInterface::findById`: expected `int`, but possibly received `int|string`.'
count = 2

[[issues]]
file = "src/CommandHandler/UpdateUserHandler.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #1 of `Webware\UserManager\Repository\UserRepositoryInterface::update`: expected `int`, but possibly received `int|string`.'
count = 1

[[issues]]
file = "src/Container/Configuration.php"
code = "imprecise-type"
message = "Type `array` in return type of `getCredentialConfig` is imprecise, equivalent to `array<array-key, mixed>`."
count = 1

[[issues]]
file = "src/Container/Configuration.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "class-must-be-final"
message = 'Class `Webware\UserManager\Entity\User` should be declared `final`.'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "docblock-parameter-narrowing"
message = "Docblock type `array<string, mixed>|null` for parameter `$details` drops part of native type `array<array-key, mixed>|null|string`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "incompatible-parameter-type"
message = 'Parameter `$data` of `Webware\UserManager\Entity\User::populate()` expects type `array<string, mixed>` but parent `PhpDb\ResultSet\RowPrototypeInterface::populate()` expects type `array<array-key, mixed>`'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "invalid-property-assignment-value"
message = "Invalid type for property `$details`: expected `array<string, mixed>|null`, but got `list{string}`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "invalid-property-assignment-value"
message = "Invalid type for property `$tokenCreatedAt`: expected `DateTimeImmutable|array<array-key, mixed>|null|string`, but got `DateTimeImmutable|false`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `Webware\UserManager\Entity\User::getDetails`: expected `array<string, mixed>`, but found `array<string, mixed>|null`.'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `Webware\UserManager\Entity\User::getOwnerId`: expected `int|null`, but found `int|null|string`.'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `Webware\UserManager\Entity\User::getRoleId`: expected `string`, but found `array<array-key, mixed>|null|string`.'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "invalid-type-cast"
message = 'Object of type `$this(Webware\UserManager\Entity\User)` cast to `array`. Property visibility (public, protected, private) affects the resulting array.'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "less-specific-nested-return-statement"
message = '''Returned type `array<array-key, mixed>|null|string` is less specific than the declared return type `array<array-key, Laminas\Permissions\Acl\Role\RoleInterface>|null` for function `Webware\UserManager\Entity\User::getRoles` due to nested 'mixed'.'''
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `DateTimeImmutable::__construct`: expected `string`, but found `nonnull`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `DateTimeZone::__construct`: expected `string`, but found `mixed`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `DateTimeZone::__construct`: expected `string`, but found `nonnull`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "mixed-argument"
message = "Invalid argument type for argument #2 of `DateTimeImmutable::createFromFormat`: expected `string`, but found `nonnull`."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 2

[[issues]]
file = "src/Entity/User.php"
code = "nullable-return-statement"
message = 'Function `Webware\UserManager\Entity\User::getDetails` is declared to return `array<string, mixed>` but possibly returns a nullable value (inferred as `array<string, mixed>|null`).'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "nullable-return-statement"
message = 'Function `Webware\UserManager\Entity\User::getRoleId` is declared to return `string` but possibly returns a nullable value (inferred as `array<array-key, mixed>|null|string`).'
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "property-type-coercion"
message = "A value of a less specific type `array<array-key, mixed>` is being assigned to property `$details` (array<string, mixed>|null)."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "property-type-coercion"
message = "A value of a less specific type `array<array-key, mixed>|null` is being assigned to property `$details` (array<string, mixed>|null)."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "redundant-comparison"
message = "Redundant `===` comparison: left-hand side is always identical to right-hand side."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "redundant-comparison"
message = "Redundant `===` comparison: left-hand side is never identical to right-hand side."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "redundant-condition"
message = "This condition (type `true`) will always evaluate to true."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "redundant-logical-operation"
message = "Redundant `||` operation: left operand is evaluated and right operand is always truthy."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "unsafe-instantiation"
message = 'Unsafe `new static()`: constructor of `Webware\UserManager\Entity\User` is not final and its signature might change in child classes, potentially leading to runtime errors.'
count = 10

[[issues]]
file = "src/Event/SendVerificationEmailEvent.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `Webware\UserManager\Event\SendVerificationEmailEvent::getToken`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Event/SendVerificationEmailEvent.php"
code = "non-existent-property"
message = 'Property `$verificationToken` does not exist on class `Webware\UserManager\Command\UpdateUserCommand`.'
count = 1

[[issues]]
file = "src/Http/Admin/Middleware/ProcessToggleUserActiveMiddleware.php"
code = "possibly-false-argument"
message = 'Argument #1 of method `Webware\UserManager\Command\ToggleUserActiveCommand::__construct` is possibly `false`, but parameter type `int` does not accept it.'
count = 1

[[issues]]
file = "src/Http/Admin/RequestHandler/ToggleUserActiveHandler.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Http/Middleware/Container/LoginMiddlewareFactory.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #3 of `Webware\UserManager\Http\Middleware\LoginMiddleware::__construct`: expected `string`, but found `nonnull`.'
count = 1

[[issues]]
file = "src/Http/Middleware/Container/LoginMiddlewareFactory.php"
code = "mixed-assignment"
message = "Assigning `nonnull` type to a variable may lead to unexpected behavior."
count = 2

[[issues]]
file = "src/Http/Middleware/IdentityMiddleware.php"
code = "missing-property-type"
message = "Property `$userFactory` is missing a type hint."
count = 1

[[issues]]
file = "src/Http/Middleware/LoginMiddleware.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 3

[[issues]]
file = "src/Http/Middleware/LoginMiddleware.php"
code = "mixed-method-access"
message = "Attempting to access a method on a non-object type (`mixed`)."
count = 2

[[issues]]
file = "src/Http/Middleware/LoginMiddleware.php"
code = "possible-method-access-on-null"
message = "Attempting to call a method on `null`."
count = 1

[[issues]]
file = "src/Http/RequestHandler/Container/LogoutHandlerFactory.php"
code = "redundant-docblock-type"
message = "Redundant docblock type for variable `$helperManager`."
count = 1

[[issues]]
file = "src/Http/RequestHandler/Container/RegistrationHandlerFactory.php"
code = "redundant-docblock-type"
message = "Redundant docblock type for variable `$helperManager`."
count = 1

[[issues]]
file = "src/Http/RequestHandler/LoginHandler.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Http/RequestHandler/LoginHandler.php"
code = "mixed-method-access"
message = "Attempting to access a method on a non-object type (`mixed`)."
count = 1

[[issues]]
file = "src/Http/RequestHandler/RegistrationHandler.php"
code = "redundant-comparison"
message = "Redundant `!==` comparison: left-hand side is always not identical to right-hand side."
count = 1

[[issues]]
file = "src/Http/RequestHandler/RegistrationHandler.php"
code = "redundant-logical-operation"
message = "Redundant `&&` operation: left operand is always truthy and right operand is evaluated."
count = 1

[[issues]]
file = "src/Http/RequestHandler/UserListHandler.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Http/RequestHandler/UserListHandler.php"
code = "possibly-false-argument"
message = 'Argument #2 of method `Laminas\Diactoros\MessageTrait::withHeader` is possibly `false`, but parameter type `array<array-key, string>|string` does not accept it.'
count = 1

[[issues]]
file = "src/Listener/Container/SendVerificationEmailListenerFactory.php"
code = "redundant-docblock-type"
message = "Redundant docblock type for variable `$helperManager`."
count = 1

[[issues]]
file = "src/Listener/SendVerificationEmailListener.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Listener/SendVerificationEmailListener.php"
code = "non-existent-property"
message = 'Property `$verificationToken` does not exist on class `Webware\UserManager\Command\UpdateUserCommand`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "invalid-type-cast"
message = 'Object of type `Webware\MessageBus\Command\CommandInterface` cast to `array`. Property visibility (public, protected, private) affects the resulting array.'
count = 2

[[issues]]
file = "src/Repository/UserRepository.php"
code = "less-specific-argument"
message = 'Argument type mismatch for argument #2 of `Webware\UserManager\Auth\AuthenticationResult::__construct`: expected `(Webware\Core\UserInterface&Webware\UserManager\Entity\User)|null`, but provided type `Webware\Core\UserInterface` is less specific.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-argument"
message = "Invalid argument type for argument #2 of `password_verify`: expected `string`, but found `mixed`."
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-operand"
message = "Casting `mixed` to `bool`."
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `Webware\UserManager\Repository\UserRepository::findByConfiguredCredential`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `Webware\UserManager\Repository\UserRepository::findByEmail`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `Webware\UserManager\Repository\UserRepository::findById`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `Webware\UserManager\Repository\UserRepository::findByVerificationToken`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "non-existent-property"
message = 'Property `$active` does not exist on interface `Webware\Core\UserInterface`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "non-existent-property"
message = 'Property `$firstName` does not exist on interface `Webware\Core\UserInterface`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "non-existent-property"
message = 'Property `$id` does not exist on interface `Webware\MessageBus\Command\CommandInterface`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "non-existent-property"
message = 'Property `$lastName` does not exist on interface `Webware\Core\UserInterface`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "non-existent-property"
message = 'Property `$passwordHash` does not exist on interface `Webware\Core\UserInterface`.'
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "possible-method-access-on-null"
message = "Attempting to call a method on `null`."
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "redundant-comparison"
message = "Redundant `!==` comparison: left-hand side is always not identical to right-hand side."
count = 1

[[issues]]
file = "src/Repository/UserRepository.php"
code = "redundant-condition"
message = "This condition (type `true`) will always evaluate to true."
count = 1

[[issues]]
file = "src/Repository/UserRepositoryFactory.php"
code = "possibly-undefined-string-array-index"
message = "Possibly undefined array key `string('username')` accessed on `array<array-key, mixed>`."
count = 1

[[issues]]
file = "src/Repository/UserRepositoryInterface.php"
code = "missing-api-or-internal"
message = 'Interface `Webware\UserManager\Repository\UserRepositoryInterface` is missing an `@api` or `@internal` annotation.'
count = 1

[[issues]]
file = "src/RouteProvider.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #3 of `Mezzio\Router\RouteCollectorInterface::get`: expected `non-empty-string|null`, but possibly received `string`.'
count = 1

[[issues]]
file = "src/View/Helper/UserAdminUrl.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #1 of `Mezzio\Helper\UrlHelper::__invoke`: expected `non-empty-string|null`, but possibly received `string`.'
count = 1

[[issues]]
file = "src/View/Helper/UserUrl.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #1 of `Mezzio\Helper\UrlHelper::__invoke`: expected `non-empty-string|null`, but possibly received `string`.'
count = 1

[[issues]]
file = "vendor/webware/message-bus/src/Command/NamedCommandTrait.php"
code = "uninitialized-property"
message = 'Property `$name` is not initialized in the constructor of class `Webware\UserManager\Command\CreateUserCommand`.'
count = 1

[[issues]]
file = "vendor/webware/message-bus/src/Command/NamedCommandTrait.php"
code = "uninitialized-property"
message = 'Property `$name` is not initialized in the constructor of class `Webware\UserManager\Command\ToggleUserActiveCommand`.'
count = 1

[[issues]]
file = "vendor/webware/message-bus/src/Command/NamedCommandTrait.php"
code = "uninitialized-property"
message = 'Property `$name` is not initialized in the constructor of class `Webware\UserManager\Command\UpdateUserCommand`.'
count = 1

[[issues]]
file = "vendor/webware/message-bus/src/Command/NamedCommandTrait.php"
code = "uninitialized-property"
message = 'Property `$name` is not initialized in the constructor of class `Webware\UserManager\Entity\User`.'
count = 1
