variant = "loose"

[[issues]]
file = "src/Admin/Dashboard/RegisterWidgetListener.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "ambiguous-constant-access"
message = "Ambiguous constant access detected."
count = 1

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 4

[[issues]]
file = "src/Command/CreateUserCommand.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/CommandHandler/CreateUserHandler.php"
code = "no-assign-in-condition"
message = "Avoid assignments in conditions."
count = 1

[[issues]]
file = "src/ConfigProvider.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 1

[[issues]]
file = "src/Container/Configuration.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/Entity/User.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 7

[[issues]]
file = "src/Entity/User.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 2

[[issues]]
file = "src/Entity/User.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/Entity/User.php"
code = "no-negated-ternary"
message = "Negated ternary condition."
count = 1

[[issues]]
file = "src/Http/Admin/Middleware/ProcessUpdateUserMiddleware.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Http/Admin/RequestHandler/UpdateUserModalHandler.php"
code = "ambiguous-constant-access"
message = "Ambiguous constant access detected."
count = 1

[[issues]]
file = "src/Http/Middleware/IdentityMiddleware.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 2

[[issues]]
file = "src/Repository/UserRepository.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1
